name: Qodana

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build with Maven
        #env:
          #DEV_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
          #DEV_USERNAME: ${{ secrets.PROD_USERNAME }}
          #DEV_PASSWORD: ${{ secrets.PROD_PASSWORD }}
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1

  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1184424061 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
